// Disposable/temporary email domain blocklist
// These domains provide throwaway addresses commonly used to abuse trial periods

const DISPOSABLE_DOMAINS = new Set([
  // Major disposable services
  "tempmail.com", "temp-mail.org", "temp-mail.io", "tempail.com",
  "guerrillamail.com", "guerrillamail.net", "guerrillamail.org", "guerrillamail.de",
  "guerrillamailblock.com", "grr.la", "sharklasers.com", "guerrilla.ml",
  "mailinator.com", "mailinator.net", "mailinator2.com",
  "yopmail.com", "yopmail.fr", "yopmail.net", "yopmail.gq",
  "throwaway.email", "throwaway.me",
  "10minutemail.com", "10minutemail.net", "10minute.email",
  "20minutemail.com", "20minutemail.it",
  "trashmail.com", "trashmail.me", "trashmail.net", "trashmail.org",
  "dispostable.com",
  "maildrop.cc", "maildrop.ml",
  "mailnesia.com",
  "tempinbox.com",
  "fakeinbox.com",
  "sharklasers.com",
  "guerrillamailblock.com",
  "crazymailing.com",
  "disposableemailaddresses.emailmiser.com",

  // Russian-popular disposable services
  "temp-mail.ru", "tempmail.ru",
  "mailnator.com",
  "mohmal.com",
  "getnada.com",
  "emailondeck.com",
  "tempr.email",
  "discard.email",
  "discardmail.com",
  "discardmail.de",
  "disposableaddress.com",

  // Burner/anonymous services
  "burnermail.io",
  "mailcatch.com",
  "mytemp.email",
  "tempmailo.com",
  "tempmailaddress.com",
  "emailfake.com",
  "generator.email",
  "inboxkitten.com",
  "minutemail.com",
  "33mail.com",
  "getairmail.com",
  "mailexpire.com",
  "mailforspam.com",
  "safetymail.info",
  "spam4.me",
  "spamgourmet.com",
  "trashinbox.com",
  "meltmail.com",
  "harakirimail.com",
  "mailnull.com",
  "spamfree24.org",
  "jetable.org",
  "spamcero.com",

  // Other common disposable providers
  "mailsac.com",
  "mailslurp.com",
  "receiveee.com",
  "tmpmail.net", "tmpmail.org",
  "bupmail.com",
  "clrmail.com",
  "dropmail.me",
  "emkei.cz",
  "fakemail.net",
  "fixmail.tk",
  "flirtto.com",
  "jourrapide.com",
  "kurzepost.de",
  "mail-temporaire.fr",
  "mailtemp.info",
  "mailzilla.com",
  "mfsa.ru", "mfsa.info",
  "nomail.xl.cx",
  "nospam.ze.tc",
  "objectmail.com",
  "proxymail.eu",
  "rcpt.at",
  "reallymymail.com",
  "recode.me",
  "regbypass.com",
  "rhyta.com",
  "s0ny.net",
  "spaml.com",
  "superrito.com",
  "tafmail.com",
  "teleworm.us",
  "tempomail.fr",
  "temporaryemail.net",
  "temporaryforwarding.com",
  "temporaryinbox.com",
  "temporarymailaddress.com",
  "thankyou2010.com",
  "thisisnotmyrealemail.com",
  "tmail.ws",
  "tmails.net",
  "trash-amil.com",
  "trashymail.com", "trashymail.net",
  "wegwerfmail.de", "wegwerfmail.net", "wegwerfmail.org",
  "wh4f.org",
  "yapped.net",
  "za.com",

  // Catch-all pattern domains
  "mailbox.in.ua",
  "cuvox.de",
  "dayrep.com",
  "einrot.com",
  "fleckens.hu",
  "gustr.com",
  "jourrapide.com",
  "superrito.com",
  "armyspy.com",
]);

/**
 * Check if an email uses a disposable/temporary domain.
 * Returns true if the email should be BLOCKED.
 */
export function isDisposableEmail(email: string): boolean {
  const domain = email.toLowerCase().split("@")[1];
  if (!domain) return false;
  return DISPOSABLE_DOMAINS.has(domain);
}
