[build]
builder = "nixpacks"
buildCommand = "npm run build"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
startCommand = "node .next/standalone/server.js"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[service]
internalPort = 3000
