[build]
builder = "nixpacks"
buildCommand = "npm run build && cp -r public .next/standalone/public && cp -r .next/static .next/standalone/.next/static"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
startCommand = "node .next/standalone/server.js"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[service]
internalPort = 3000
